require("settings")
require("plugins")
require("colorschemes")
require("colorschemes.transparent")
require("nvim-tree-config")
require("lualine-config")
require("barbar-config")
require("mappings")
require("lsp-config.null-ls")
require("lsp-config.language-servers")
require("lsp-config.vim-go-config")
-- require("lsp-config.mason-config")
require("lsp-config.nvim-cmp")
require("treesitter-config")
require("telescope-config")
require("prettier-config")
require("neogit-config")
require("toggle-term-config")
require("git-signs-config")
require("diffview-config")
-- require("tomasr/molokai")
require("comment-config")
require("colorizer-config")
