local builtin = require("telescope.builtin")
vim.keymap.set("n", "<C-p>", builtin.git_files, {})
vim.keymap.set("n", "<leader>ff", builtin.find_files, {})
vim.keymap.set("n", "<leader>fg", builtin.live_grep, {})
vim.keymap.set("n", "<leader>fb", builtin.buffers, {})
vim.keymap.set("n", "<leader>fh", builtin.help_tags, {})
vim.keymap.set("n", "<leader>fc", builtin.commands, {})
-- vim.keymap.set("n", "<leader>fr", builtin.lsp_references, {})
vim.keymap.set("n", "gr", builtin.lsp_references, {})
vim.keymap.set("n", "<leader>ft", ":TodoTelescope<CR>", {})
-- vim.keymap.set("n", "<leader>gd", builtin.lsp_definitions, {})
vim.keymap.set("n", "gd", builtin.lsp_definitions, {})
-- vim.keymap.set("n", "<leader>gi", builtin.lsp_implementations, {})
vim.keymap.set("n", "gi", builtin.lsp_implementations, {})
-- vim.keymap.set("n", "<leader>gt", builtin.lsp_type_definitions, {})
vim.keymap.set("n", "gt", builtin.lsp_type_definitions, {})
-- vim.keymap.set("n", "<leader>fd", builtin.lsp_definitions, {})
